# ---------------------- #
# site config            #
# ---------------------- #
name: 叶子
baseurl:
tagline: 闲言碎语
author: Perry Yeh
url: https://blog.yeh.sh
urlyeh: https://www.yeh.sh
keywords: Perry Yeh
description: Whenever possible, find someone to save, and save them.
permalink: /post/:year/:month/:day/:title:output_ext
paginate: 3
paginate_path: /page/:num/
excerpt_separator: '\n\n'

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
rouge: true
markdown: kramdown
timezone: America/Los_Angeles

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

# ---------------------- #
# comments               #
# ---------------------- #
comments: yeh

# ---------------------- #
# analytics              #
# ---------------------- #
analytics: UA
